export default function Head() {
  return (
    <>
      <title>Bluedit</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="favicon.ico" />
      <base href="/" target="_blank" />
    </>
  );
}
