import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Header } from "./header";
import { Menu } from "./menu";
import { Posts } from "../components/posts";
import { MobileNav } from "./mobile-nav";

export const Layout = ({ children, title }) => {
  return (
    <div className="w-full">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <MobileNav />
      <div className=" h-full flex items-center justify-center">
        <main className="grid lg:grid-cols-4 gap-6 max-w-[1200px] w-full mt-2">
          <Menu />
          <Posts />
          {children}
        </main>
      </div>
    </div>
  );
};
